<p><a href="/admin/index" class="link">Вернуться на главную</a></p>
<p><a href="/admin/update" class="link">Редактировать пользователя</a></p>
<h1>Создать пользователя</h1>

<form action="/admin/create" method="post" enctype="multipart/form-data">
    <input type="text" name="name" placeholder="Введите имя"><br><br>
    <input type="text" name="email" placeholder="Введите email"><br><br>
    <input type="password" name="password" placeholder="Введите пароль"><br><br>
    <input type="password" name="repeatedPassword" placeholder="Повторите пароль"><br><br>
    Прикрепите картинку: <input name="userFile" type="file"/><br><br>
    <input type="submit" name="submit" value="Создать">
</form>
<br>
<br>

<?php if (isset($errors)): ?>
    <?php foreach ($errors as $error): ?>
        <span style="color: red"><?= $errorDescription[$error]; ?></span>
    <?php endforeach; ?>
<?php endif; ?>



<style>
    .link {
        color: black;
        text-decoration: none;
    }

    .link:hover {
        text-decoration: underline;
    }
</style>